<?php

class Constant
{
    const MAX_EXECUTION_TIME = 60;
    const MAX_LIMIT = 100;
    const MIN_LIMIT = 10;
    const OFFSET = 0;
    const CACHE_KEY_TOTAL_USER = 'TOTAL_USERS';
    const CACHE_KEY_TOTAL_TRANSPORT = 'TOTAL_TRANSPORT';
    const CACHE_KEY_TOTAL_PHOTO = 'TOTAL_PHOTO';
    const CACHE_KEY_TOTAL_WEDDINGDRESS = 'TOTAL_WEDDINGDRESS';
}